
model_name: "gpt2-xl"  # your own path
model_class: AutoModelForCausalLM
tokenizer_class: GPT2Tokenizer

device: 0

layers: []
num_steps: 9
#5,7,9
batch_size: 1


# max_length is the maximum length of this LLM (gpt2-xl).
max_length: 1024

max_output_length: 512


lr: 5e-4
weight_decay: 0
kl_factor: 0.1
norm_constraint: false
rewrite_module_tmp: "transformer.h.{}.mlp.c_proj"
layer_module_tmp: "transformer.h.{}"
mlp_module_tmp: "transformer.h.{}.mlp"
attn_module_tmp: "transformer.h.{}.attn"
ln_f_module: "transformer.ln_f"
lm_head_module: "transformer.wte"
model_parallel: false



