
model_name: "Llama-3-8b-instruct"  # the vanilla LLM path
model_class: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
device: 0

layers: []
num_steps: 7
batch_size: 1



# max_length is the maximum length of this LLM (llama3-8b-instruct).
max_length: 2048

max_output_length: 512

lr: 5e-5 #5e-4  5e-5√  7e-5√
weight_decay: 0
kl_factor: 0.1
norm_constraint: false
rewrite_module_tmp: 'model.layers.{}.mlp.down_proj.weight'
layer_module_tmp: 'model.layers.{}'
mlp_module_tmp: 'model.layers.{}.mlp'
attn_module_tmp: 'model.layers.{}.self_attn'
ln_f_module: 'model.norm'
lm_head_module: 'lm_head'
model_parallel: false
