
model_name: "mistral-7B-v0.1"  # the vanilla LLM path
model_class: AutoModelForCausalLM
tokenizer_class: AutoTokenizer
device: 0

layers: []
num_steps: 14
batch_size: 1

# max_length is the maximum length of this LLM (Mistral-7B-v0.1).
max_length: 2048

max_output_length: 512


lr: 1e-5
weight_decay: 0
kl_factor: 0.1
norm_constraint: false
rewrite_module_tmp: 'model.layers.{}.mlp.down_proj.weight'
layer_module_tmp: 'model.layers.{}'
mlp_module_tmp: 'model.layers.{}.mlp'
attn_module_tmp: 'model.layers.{}.self_attn'
ln_f_module: 'model.norm'
lm_head_module: 'lm_head'
model_parallel: false
